package com.example.demo.mapper;

import com.example.demo.pojo.AcctUser;
import com.example.demo.pojo.AcctUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AcctUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    long countByExample(AcctUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int deleteByExample(AcctUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int insert(AcctUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int insertSelective(AcctUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    List<AcctUser> selectByExample(AcctUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    AcctUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") AcctUser record, @Param("example") AcctUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByExample(@Param("record") AcctUser record, @Param("example") AcctUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByPrimaryKeySelective(AcctUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByPrimaryKey(AcctUser record);


    // 查询用户信息
    AcctUser findByName(String name);

    // 查询用户信息、角色、权限
    AcctUser findById(Long id);
}