package com.example.demo.mapper;

import com.example.demo.pojo.AcctRoleAuthotity;
import com.example.demo.pojo.AcctRoleAuthotityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AcctRoleAuthotityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    long countByExample(AcctRoleAuthotityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int deleteByExample(AcctRoleAuthotityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int insert(AcctRoleAuthotity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int insertSelective(AcctRoleAuthotity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    List<AcctRoleAuthotity> selectByExample(AcctRoleAuthotityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") AcctRoleAuthotity record, @Param("example") AcctRoleAuthotityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByExample(@Param("record") AcctRoleAuthotity record, @Param("example") AcctRoleAuthotityExample example);
}