package com.example.demo.mapper;

import com.example.demo.pojo.AcctRole;
import com.example.demo.pojo.AcctRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AcctRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    long countByExample(AcctRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int deleteByExample(AcctRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int insert(AcctRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int insertSelective(AcctRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    List<AcctRole> selectByExample(AcctRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    AcctRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") AcctRole record, @Param("example") AcctRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByExample(@Param("record") AcctRole record, @Param("example") AcctRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByPrimaryKeySelective(AcctRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    int updateByPrimaryKey(AcctRole record);
}