package com.example.demo.mapper;

import com.example.demo.pojo.HMedicalExamine;
import com.example.demo.pojo.HMedicalExamineExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HMedicalExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    long countByExample(HMedicalExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int deleteByExample(HMedicalExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int insert(HMedicalExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int insertSelective(HMedicalExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    List<HMedicalExamine> selectByExample(HMedicalExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    HMedicalExamine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") HMedicalExamine record, @Param("example") HMedicalExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int updateByExample(@Param("record") HMedicalExamine record, @Param("example") HMedicalExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int updateByPrimaryKeySelective(HMedicalExamine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    int updateByPrimaryKey(HMedicalExamine record);
}