package com.example.demo.mapper;


import com.example.demo.pojo.TimeTest;
import com.example.demo.pojo.TimeTestExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TimeTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    long countByExample(TimeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int deleteByExample(TimeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int insert(TimeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int insertSelective(TimeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    List<TimeTest> selectByExample(TimeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    TimeTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") TimeTest record, @Param("example") TimeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int updateByExample(@Param("record") TimeTest record, @Param("example") TimeTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int updateByPrimaryKeySelective(TimeTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_test
     *
     * @mbg.generated Mon Oct 21 11:13:31 CST 2019
     */
    int updateByPrimaryKey(TimeTest record);
}