package com.example.demo.mapper.test01;

import com.example.demo.pojo.TNavigation;
import com.example.demo.pojo.TNavigationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TNavigationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    long countByExample(TNavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int deleteByExample(TNavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int deleteByPrimaryKey(Long navigationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int insert(TNavigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int insertSelective(TNavigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    List<TNavigation> selectByExample(TNavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    TNavigation selectByPrimaryKey(Long navigationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") TNavigation record, @Param("example") TNavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int updateByExample(@Param("record") TNavigation record, @Param("example") TNavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int updateByPrimaryKeySelective(TNavigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    int updateByPrimaryKey(TNavigation record);
}