package com.example.demo.mapper.test03;

import com.example.demo.pojo.TonlineUser;
import com.example.demo.pojo.TonlineUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TonlineUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    long countByExample(TonlineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    int deleteByExample(TonlineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    int insert(TonlineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    int insertSelective(TonlineUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    List<TonlineUser> selectByExample(TonlineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") TonlineUser record, @Param("example") TonlineUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    int updateByExample(@Param("record") TonlineUser record, @Param("example") TonlineUserExample example);
}