package com.example.demo.pojo;

public class AcctUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user_role.user_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user_role.role_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user_role.user_id
     *
     * @return the value of acct_user_role.user_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user_role.user_id
     *
     * @param userId the value for acct_user_role.user_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user_role.role_id
     *
     * @return the value of acct_user_role.role_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user_role.role_id
     *
     * @param roleId the value for acct_user_role.role_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user_role
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append("]");
        return sb.toString();
    }
}