package com.example.demo.pojo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

public class AcctUser implements Serializable {

    private Set<AcctRole> roles = new HashSet<>();

    public Set<AcctRole> getRoles() {
        return roles;
    }

    public void setRoles(Set<AcctRole> roles) {
        this.roles = roles;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.email
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.login_name
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.name
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.password
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.address
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.age
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.department
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.gender
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.identity_num
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String identityNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_user.tel
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.id
     *
     * @return the value of acct_user.id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.id
     *
     * @param id the value for acct_user.id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.email
     *
     * @return the value of acct_user.email
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.email
     *
     * @param email the value for acct_user.email
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.login_name
     *
     * @return the value of acct_user.login_name
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.login_name
     *
     * @param loginName the value for acct_user.login_name
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.name
     *
     * @return the value of acct_user.name
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.name
     *
     * @param name the value for acct_user.name
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.password
     *
     * @return the value of acct_user.password
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.password
     *
     * @param password the value for acct_user.password
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.address
     *
     * @return the value of acct_user.address
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.address
     *
     * @param address the value for acct_user.address
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.age
     *
     * @return the value of acct_user.age
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.age
     *
     * @param age the value for acct_user.age
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.department
     *
     * @return the value of acct_user.department
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.department
     *
     * @param department the value for acct_user.department
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.gender
     *
     * @return the value of acct_user.gender
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.gender
     *
     * @param gender the value for acct_user.gender
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.identity_num
     *
     * @return the value of acct_user.identity_num
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getIdentityNum() {
        return identityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.identity_num
     *
     * @param identityNum the value for acct_user.identity_num
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setIdentityNum(String identityNum) {
        this.identityNum = identityNum == null ? null : identityNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_user.tel
     *
     * @return the value of acct_user.tel
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_user.tel
     *
     * @param tel the value for acct_user.tel
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_user
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", email=").append(email);
        sb.append(", loginName=").append(loginName);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", address=").append(address);
        sb.append(", age=").append(age);
        sb.append(", department=").append(department);
        sb.append(", gender=").append(gender);
        sb.append(", identityNum=").append(identityNum);
        sb.append(", tel=").append(tel);
        sb.append("]");
        return sb.toString();
    }
}