package com.example.demo.pojo;

public class AcctRoleAuthotity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_role_authority.role_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acct_role_authority.authority_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    private Long authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_role_authority.role_id
     *
     * @return the value of acct_role_authority.role_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_role_authority.role_id
     *
     * @param roleId the value for acct_role_authority.role_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acct_role_authority.authority_id
     *
     * @return the value of acct_role_authority.authority_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public Long getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acct_role_authority.authority_id
     *
     * @param authorityId the value for acct_role_authority.authority_id
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    public void setAuthorityId(Long authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acct_role_authority
     *
     * @mbg.generated Sun Sep 29 10:58:18 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", authorityId=").append(authorityId);
        sb.append("]");
        return sb.toString();
    }
}