package com.example.demo.pojo;

import com.example.demo.util.ExcelColumn;

import java.io.Serializable;

public class HMedicalExamine implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_medical_examine.id
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    @ExcelColumn(value = "主键", col = 1)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_medical_examine.department
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    @ExcelColumn(value = "部门", col = 2)
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_medical_examine.price
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    @ExcelColumn(value = "价格", col = 3)
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_medical_examine.project_name
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    @ExcelColumn(value = "项目", col = 4)
    private String projectName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_medical_examine.id
     *
     * @return the value of h_medical_examine.id
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_medical_examine.id
     *
     * @param id the value for h_medical_examine.id
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_medical_examine.department
     *
     * @return the value of h_medical_examine.department
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_medical_examine.department
     *
     * @param department the value for h_medical_examine.department
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_medical_examine.price
     *
     * @return the value of h_medical_examine.price
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_medical_examine.price
     *
     * @param price the value for h_medical_examine.price
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_medical_examine.project_name
     *
     * @return the value of h_medical_examine.project_name
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_medical_examine.project_name
     *
     * @param projectName the value for h_medical_examine.project_name
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_medical_examine
     *
     * @mbg.generated Wed Sep 18 10:24:17 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", department=").append(department);
        sb.append(", price=").append(price);
        sb.append(", projectName=").append(projectName);
        sb.append("]");
        return sb.toString();
    }
}