package com.example.demo.pojo;

import com.example.demo.util.ExcelColumn;

import java.io.Serializable;

public class personInfor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_infor.id
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    @ExcelColumn(value = "主键", col = 1)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_infor.name
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    @ExcelColumn(value = "名字", col = 2)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_infor.age
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    @ExcelColumn(value = "年龄", col = 3)
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_infor.id
     *
     * @return the value of person_infor.id
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_infor.id
     *
     * @param id the value for person_infor.id
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_infor.name
     *
     * @return the value of person_infor.name
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_infor.name
     *
     * @param name the value for person_infor.name
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_infor.age
     *
     * @return the value of person_infor.age
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_infor.age
     *
     * @param age the value for person_infor.age
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_infor
     *
     * @mbg.generated Thu Jun 04 09:19:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append("]");
        return sb.toString();
    }
}