package com.example.demo.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TNavigationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public TNavigationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNavigationIdIsNull() {
            addCriterion("navigation_id is null");
            return (Criteria) this;
        }

        public Criteria andNavigationIdIsNotNull() {
            addCriterion("navigation_id is not null");
            return (Criteria) this;
        }

        public Criteria andNavigationIdEqualTo(Long value) {
            addCriterion("navigation_id =", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdNotEqualTo(Long value) {
            addCriterion("navigation_id <>", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdGreaterThan(Long value) {
            addCriterion("navigation_id >", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("navigation_id >=", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdLessThan(Long value) {
            addCriterion("navigation_id <", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdLessThanOrEqualTo(Long value) {
            addCriterion("navigation_id <=", value, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdIn(List<Long> values) {
            addCriterion("navigation_id in", values, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdNotIn(List<Long> values) {
            addCriterion("navigation_id not in", values, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdBetween(Long value1, Long value2) {
            addCriterion("navigation_id between", value1, value2, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationIdNotBetween(Long value1, Long value2) {
            addCriterion("navigation_id not between", value1, value2, "navigationId");
            return (Criteria) this;
        }

        public Criteria andNavigationNameIsNull() {
            addCriterion("navigation_name is null");
            return (Criteria) this;
        }

        public Criteria andNavigationNameIsNotNull() {
            addCriterion("navigation_name is not null");
            return (Criteria) this;
        }

        public Criteria andNavigationNameEqualTo(String value) {
            addCriterion("navigation_name =", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotEqualTo(String value) {
            addCriterion("navigation_name <>", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameGreaterThan(String value) {
            addCriterion("navigation_name >", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameGreaterThanOrEqualTo(String value) {
            addCriterion("navigation_name >=", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameLessThan(String value) {
            addCriterion("navigation_name <", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameLessThanOrEqualTo(String value) {
            addCriterion("navigation_name <=", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameLike(String value) {
            addCriterion("navigation_name like", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotLike(String value) {
            addCriterion("navigation_name not like", value, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameIn(List<String> values) {
            addCriterion("navigation_name in", values, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotIn(List<String> values) {
            addCriterion("navigation_name not in", values, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameBetween(String value1, String value2) {
            addCriterion("navigation_name between", value1, value2, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationNameNotBetween(String value1, String value2) {
            addCriterion("navigation_name not between", value1, value2, "navigationName");
            return (Criteria) this;
        }

        public Criteria andNavigationColourIsNull() {
            addCriterion("navigation_colour is null");
            return (Criteria) this;
        }

        public Criteria andNavigationColourIsNotNull() {
            addCriterion("navigation_colour is not null");
            return (Criteria) this;
        }

        public Criteria andNavigationColourEqualTo(String value) {
            addCriterion("navigation_colour =", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourNotEqualTo(String value) {
            addCriterion("navigation_colour <>", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourGreaterThan(String value) {
            addCriterion("navigation_colour >", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourGreaterThanOrEqualTo(String value) {
            addCriterion("navigation_colour >=", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourLessThan(String value) {
            addCriterion("navigation_colour <", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourLessThanOrEqualTo(String value) {
            addCriterion("navigation_colour <=", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourLike(String value) {
            addCriterion("navigation_colour like", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourNotLike(String value) {
            addCriterion("navigation_colour not like", value, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourIn(List<String> values) {
            addCriterion("navigation_colour in", values, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourNotIn(List<String> values) {
            addCriterion("navigation_colour not in", values, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourBetween(String value1, String value2) {
            addCriterion("navigation_colour between", value1, value2, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andNavigationColourNotBetween(String value1, String value2) {
            addCriterion("navigation_colour not between", value1, value2, "navigationColour");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Long value) {
            addCriterion("pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Long value) {
            addCriterion("pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Long value) {
            addCriterion("pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Long value) {
            addCriterion("pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Long value) {
            addCriterion("pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Long value) {
            addCriterion("pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Long> values) {
            addCriterion("pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Long> values) {
            addCriterion("pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Long value1, Long value2) {
            addCriterion("pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Long value1, Long value2) {
            addCriterion("pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andNaLevelIsNull() {
            addCriterion("na_level is null");
            return (Criteria) this;
        }

        public Criteria andNaLevelIsNotNull() {
            addCriterion("na_level is not null");
            return (Criteria) this;
        }

        public Criteria andNaLevelEqualTo(Integer value) {
            addCriterion("na_level =", value, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelNotEqualTo(Integer value) {
            addCriterion("na_level <>", value, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelGreaterThan(Integer value) {
            addCriterion("na_level >", value, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("na_level >=", value, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelLessThan(Integer value) {
            addCriterion("na_level <", value, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelLessThanOrEqualTo(Integer value) {
            addCriterion("na_level <=", value, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelIn(List<Integer> values) {
            addCriterion("na_level in", values, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelNotIn(List<Integer> values) {
            addCriterion("na_level not in", values, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelBetween(Integer value1, Integer value2) {
            addCriterion("na_level between", value1, value2, "naLevel");
            return (Criteria) this;
        }

        public Criteria andNaLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("na_level not between", value1, value2, "naLevel");
            return (Criteria) this;
        }

        public Criteria andSortNumIsNull() {
            addCriterion("sort_num is null");
            return (Criteria) this;
        }

        public Criteria andSortNumIsNotNull() {
            addCriterion("sort_num is not null");
            return (Criteria) this;
        }

        public Criteria andSortNumEqualTo(Integer value) {
            addCriterion("sort_num =", value, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumNotEqualTo(Integer value) {
            addCriterion("sort_num <>", value, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumGreaterThan(Integer value) {
            addCriterion("sort_num >", value, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sort_num >=", value, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumLessThan(Integer value) {
            addCriterion("sort_num <", value, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumLessThanOrEqualTo(Integer value) {
            addCriterion("sort_num <=", value, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumIn(List<Integer> values) {
            addCriterion("sort_num in", values, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumNotIn(List<Integer> values) {
            addCriterion("sort_num not in", values, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumBetween(Integer value1, Integer value2) {
            addCriterion("sort_num between", value1, value2, "sortNum");
            return (Criteria) this;
        }

        public Criteria andSortNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sort_num not between", value1, value2, "sortNum");
            return (Criteria) this;
        }

        public Criteria andVisitLimitIsNull() {
            addCriterion("visit_limit is null");
            return (Criteria) this;
        }

        public Criteria andVisitLimitIsNotNull() {
            addCriterion("visit_limit is not null");
            return (Criteria) this;
        }

        public Criteria andVisitLimitEqualTo(String value) {
            addCriterion("visit_limit =", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitNotEqualTo(String value) {
            addCriterion("visit_limit <>", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitGreaterThan(String value) {
            addCriterion("visit_limit >", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitGreaterThanOrEqualTo(String value) {
            addCriterion("visit_limit >=", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitLessThan(String value) {
            addCriterion("visit_limit <", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitLessThanOrEqualTo(String value) {
            addCriterion("visit_limit <=", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitLike(String value) {
            addCriterion("visit_limit like", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitNotLike(String value) {
            addCriterion("visit_limit not like", value, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitIn(List<String> values) {
            addCriterion("visit_limit in", values, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitNotIn(List<String> values) {
            addCriterion("visit_limit not in", values, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitBetween(String value1, String value2) {
            addCriterion("visit_limit between", value1, value2, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andVisitLimitNotBetween(String value1, String value2) {
            addCriterion("visit_limit not between", value1, value2, "visitLimit");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNull() {
            addCriterion("is_vaild is null");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNotNull() {
            addCriterion("is_vaild is not null");
            return (Criteria) this;
        }

        public Criteria andIsVaildEqualTo(String value) {
            addCriterion("is_vaild =", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotEqualTo(String value) {
            addCriterion("is_vaild <>", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThan(String value) {
            addCriterion("is_vaild >", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThanOrEqualTo(String value) {
            addCriterion("is_vaild >=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThan(String value) {
            addCriterion("is_vaild <", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThanOrEqualTo(String value) {
            addCriterion("is_vaild <=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLike(String value) {
            addCriterion("is_vaild like", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotLike(String value) {
            addCriterion("is_vaild not like", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildIn(List<String> values) {
            addCriterion("is_vaild in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotIn(List<String> values) {
            addCriterion("is_vaild not in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildBetween(String value1, String value2) {
            addCriterion("is_vaild between", value1, value2, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotBetween(String value1, String value2) {
            addCriterion("is_vaild not between", value1, value2, "isVaild");
            return (Criteria) this;
        }

        public Criteria andOperateIdIsNull() {
            addCriterion("operate_id is null");
            return (Criteria) this;
        }

        public Criteria andOperateIdIsNotNull() {
            addCriterion("operate_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperateIdEqualTo(String value) {
            addCriterion("operate_id =", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotEqualTo(String value) {
            addCriterion("operate_id <>", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdGreaterThan(String value) {
            addCriterion("operate_id >", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdGreaterThanOrEqualTo(String value) {
            addCriterion("operate_id >=", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdLessThan(String value) {
            addCriterion("operate_id <", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdLessThanOrEqualTo(String value) {
            addCriterion("operate_id <=", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdLike(String value) {
            addCriterion("operate_id like", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotLike(String value) {
            addCriterion("operate_id not like", value, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdIn(List<String> values) {
            addCriterion("operate_id in", values, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotIn(List<String> values) {
            addCriterion("operate_id not in", values, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdBetween(String value1, String value2) {
            addCriterion("operate_id between", value1, value2, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateIdNotBetween(String value1, String value2) {
            addCriterion("operate_id not between", value1, value2, "operateId");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("operate_time is null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("operate_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("operate_time =", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("operate_time <>", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("operate_time >", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operate_time >=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("operate_time <", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("operate_time <=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("operate_time in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("operate_time not in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("operate_time between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("operate_time not between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlIsNull() {
            addCriterion("navigation_url is null");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlIsNotNull() {
            addCriterion("navigation_url is not null");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlEqualTo(String value) {
            addCriterion("navigation_url =", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotEqualTo(String value) {
            addCriterion("navigation_url <>", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlGreaterThan(String value) {
            addCriterion("navigation_url >", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlGreaterThanOrEqualTo(String value) {
            addCriterion("navigation_url >=", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlLessThan(String value) {
            addCriterion("navigation_url <", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlLessThanOrEqualTo(String value) {
            addCriterion("navigation_url <=", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlLike(String value) {
            addCriterion("navigation_url like", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotLike(String value) {
            addCriterion("navigation_url not like", value, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlIn(List<String> values) {
            addCriterion("navigation_url in", values, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotIn(List<String> values) {
            addCriterion("navigation_url not in", values, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlBetween(String value1, String value2) {
            addCriterion("navigation_url between", value1, value2, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andNavigationUrlNotBetween(String value1, String value2) {
            addCriterion("navigation_url not between", value1, value2, "navigationUrl");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_industria_navigation
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 04 09:16:44 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}