package com.example.demo.pojo;

import java.util.Date;

public class TNavigation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.navigation_id
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private Long navigationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.navigation_name
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private String navigationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.navigation_colour
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private String navigationColour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.pid
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.na_level
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private Integer naLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.sort_num
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private Integer sortNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.visit_limit
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private String visitLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.is_vaild
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private String isVaild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.operate_id
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private String operateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.operate_time
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private Date operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.navigation_url
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private String navigationUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_industria_navigation.create_time
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.navigation_id
     *
     * @return the value of t_industria_navigation.navigation_id
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Long getNavigationId() {
        return navigationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.navigation_id
     *
     * @param navigationId the value for t_industria_navigation.navigation_id
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setNavigationId(Long navigationId) {
        this.navigationId = navigationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.navigation_name
     *
     * @return the value of t_industria_navigation.navigation_name
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public String getNavigationName() {
        return navigationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.navigation_name
     *
     * @param navigationName the value for t_industria_navigation.navigation_name
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setNavigationName(String navigationName) {
        this.navigationName = navigationName == null ? null : navigationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.navigation_colour
     *
     * @return the value of t_industria_navigation.navigation_colour
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public String getNavigationColour() {
        return navigationColour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.navigation_colour
     *
     * @param navigationColour the value for t_industria_navigation.navigation_colour
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setNavigationColour(String navigationColour) {
        this.navigationColour = navigationColour == null ? null : navigationColour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.pid
     *
     * @return the value of t_industria_navigation.pid
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.pid
     *
     * @param pid the value for t_industria_navigation.pid
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.na_level
     *
     * @return the value of t_industria_navigation.na_level
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Integer getNaLevel() {
        return naLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.na_level
     *
     * @param naLevel the value for t_industria_navigation.na_level
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setNaLevel(Integer naLevel) {
        this.naLevel = naLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.sort_num
     *
     * @return the value of t_industria_navigation.sort_num
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.sort_num
     *
     * @param sortNum the value for t_industria_navigation.sort_num
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.visit_limit
     *
     * @return the value of t_industria_navigation.visit_limit
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public String getVisitLimit() {
        return visitLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.visit_limit
     *
     * @param visitLimit the value for t_industria_navigation.visit_limit
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setVisitLimit(String visitLimit) {
        this.visitLimit = visitLimit == null ? null : visitLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.is_vaild
     *
     * @return the value of t_industria_navigation.is_vaild
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public String getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.is_vaild
     *
     * @param isVaild the value for t_industria_navigation.is_vaild
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setIsVaild(String isVaild) {
        this.isVaild = isVaild == null ? null : isVaild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.operate_id
     *
     * @return the value of t_industria_navigation.operate_id
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public String getOperateId() {
        return operateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.operate_id
     *
     * @param operateId the value for t_industria_navigation.operate_id
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setOperateId(String operateId) {
        this.operateId = operateId == null ? null : operateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.operate_time
     *
     * @return the value of t_industria_navigation.operate_time
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.operate_time
     *
     * @param operateTime the value for t_industria_navigation.operate_time
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.navigation_url
     *
     * @return the value of t_industria_navigation.navigation_url
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public String getNavigationUrl() {
        return navigationUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.navigation_url
     *
     * @param navigationUrl the value for t_industria_navigation.navigation_url
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setNavigationUrl(String navigationUrl) {
        this.navigationUrl = navigationUrl == null ? null : navigationUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_industria_navigation.create_time
     *
     * @return the value of t_industria_navigation.create_time
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_industria_navigation.create_time
     *
     * @param createTime the value for t_industria_navigation.create_time
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_industria_navigation
     *
     * @mbg.generated Thu Jun 04 09:16:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", navigationId=").append(navigationId);
        sb.append(", navigationName=").append(navigationName);
        sb.append(", navigationColour=").append(navigationColour);
        sb.append(", pid=").append(pid);
        sb.append(", naLevel=").append(naLevel);
        sb.append(", sortNum=").append(sortNum);
        sb.append(", visitLimit=").append(visitLimit);
        sb.append(", isVaild=").append(isVaild);
        sb.append(", operateId=").append(operateId);
        sb.append(", operateTime=").append(operateTime);
        sb.append(", navigationUrl=").append(navigationUrl);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}