package com.example.demo.pojo;

public class TonlineUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.USER_ID
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.TEL
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.ENTERPRISE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String enterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.USER_NAME
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.OPENING_DATE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String openingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.END_DATE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.OPERATOR_ID
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.USER_PWD
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.REAL_NAME
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TS_ONLINE_USER_18911.WECHAT_CODE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    private String wechatCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.USER_ID
     *
     * @return the value of TS_ONLINE_USER_18911.USER_ID
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.USER_ID
     *
     * @param userId the value for TS_ONLINE_USER_18911.USER_ID
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.TEL
     *
     * @return the value of TS_ONLINE_USER_18911.TEL
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.TEL
     *
     * @param tel the value for TS_ONLINE_USER_18911.TEL
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.ENTERPRISE
     *
     * @return the value of TS_ONLINE_USER_18911.ENTERPRISE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.ENTERPRISE
     *
     * @param enterprise the value for TS_ONLINE_USER_18911.ENTERPRISE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setEnterprise(String enterprise) {
        this.enterprise = enterprise == null ? null : enterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.USER_NAME
     *
     * @return the value of TS_ONLINE_USER_18911.USER_NAME
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.USER_NAME
     *
     * @param userName the value for TS_ONLINE_USER_18911.USER_NAME
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.OPENING_DATE
     *
     * @return the value of TS_ONLINE_USER_18911.OPENING_DATE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getOpeningDate() {
        return openingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.OPENING_DATE
     *
     * @param openingDate the value for TS_ONLINE_USER_18911.OPENING_DATE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setOpeningDate(String openingDate) {
        this.openingDate = openingDate == null ? null : openingDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.END_DATE
     *
     * @return the value of TS_ONLINE_USER_18911.END_DATE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.END_DATE
     *
     * @param endDate the value for TS_ONLINE_USER_18911.END_DATE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.OPERATOR_ID
     *
     * @return the value of TS_ONLINE_USER_18911.OPERATOR_ID
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.OPERATOR_ID
     *
     * @param operatorId the value for TS_ONLINE_USER_18911.OPERATOR_ID
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.USER_PWD
     *
     * @return the value of TS_ONLINE_USER_18911.USER_PWD
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.USER_PWD
     *
     * @param userPwd the value for TS_ONLINE_USER_18911.USER_PWD
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.REAL_NAME
     *
     * @return the value of TS_ONLINE_USER_18911.REAL_NAME
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.REAL_NAME
     *
     * @param realName the value for TS_ONLINE_USER_18911.REAL_NAME
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TS_ONLINE_USER_18911.WECHAT_CODE
     *
     * @return the value of TS_ONLINE_USER_18911.WECHAT_CODE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public String getWechatCode() {
        return wechatCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TS_ONLINE_USER_18911.WECHAT_CODE
     *
     * @param wechatCode the value for TS_ONLINE_USER_18911.WECHAT_CODE
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    public void setWechatCode(String wechatCode) {
        this.wechatCode = wechatCode == null ? null : wechatCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_ONLINE_USER_18911
     *
     * @mbg.generated Thu Jul 09 16:37:09 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", tel=").append(tel);
        sb.append(", enterprise=").append(enterprise);
        sb.append(", userName=").append(userName);
        sb.append(", openingDate=").append(openingDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", userPwd=").append(userPwd);
        sb.append(", realName=").append(realName);
        sb.append(", wechatCode=").append(wechatCode);
        sb.append("]");
        return sb.toString();
    }
}